### ISSUE TITLE
Multiple Masters

### ISSUE THREAD

**Issue by watchwithmike** [awslabs/eb-locustio-sample#10]
@abhiksingh I see you're poking around and I had a quick question.  When I scale beyond 40ish instances I usually end up in a situation where there appear to be 2 masters.  For example if I use `c3.large` instances (2 cpu) I would expect 79 slaves (+ 1 master).  However I occasionally end up with a Locust web interface that alternates between 65 and 13 (or something similar).  Any idea why that would happen?

**Comment by abhiksingh** [comment]
@watchwithmike I just changed the sample to use Beanstalk's deployment ID. You should no longer run into the problem you mentioned if you use the latest code. Let me know if you do and I can help debug further.
