### ISSUE TITLE
Why java?

### ISSUE THREAD

**Issue by janewilkin** [awslabs/eb-locustio-sample#4]
First of all, many MANY thanks for putting this guide together!  I'm going to use it to load test our system for the elections, and I know it's going to save my butt. 

So, if locust is a python app, why are we running it in a Java EB environment?

**Comment by rossmckelvie** [comment]
Java and Go are the only Beanstalk platforms that support the `Procfile`

**Comment by abhiksingh** [comment]
Apologies for the late response. For some reason I wasn't receiving notifications for issues on this repo.

@rossmckelvie answer is correct. I used the Java platform to make use of the procfile to enable me to run a process, in this case locust.
