### ISSUE TITLE
Upgrade locust

### ISSUE THREAD

**Issue by nnn406** [awslabs/eb-locustio-sample#7]
What is the easiest way to upgrade locust in this repo?

**Comment by watchwithmike** [comment]
Look in `.ebextensions/setup.config`, you'll see the Locust version defined there.  I recently updated mine as follows:
```
    pyzmq: [ "16.0.3" ]
    locustio: [ "0.8.1" ]
```

**Comment by yurko006** [comment]
After doing this, how does one actually upgrade the application? Do you have to do eb init again, or is there a faster way in order to do this? 

UPDATE: Figured it out. Need to zip up and redeploy the application through the elastic beanstalk console.

**Comment by watchwithmike** [comment]
`eb deploy` from the command line worked for me.  I think that does essentially the same thing.

**Comment by abhiksingh** [comment]
@watchwithmike's answer is correct.
