### ISSUE TITLE
Issue with locust framework. Wondering if anyone has seen this behavior before. 

### ISSUE THREAD

**Issue by yurko006** [awslabs/eb-locustio-sample#8]
https://github.com/locustio/locust/issues/690

**Comment by abhiksingh** [comment]
This seems like an issue with running Locust on T2 instance family has a burstable CPU model which is likely the culprit for the behavior. For more information, see https://aws.amazon.com/ec2/instance-types/#burst.

For sustained workloads such as load testing, I'd recommend the C4 or C5 instance family.

Closing as this isn't an issue with the sample.
